[options]
focus_follows_mouse = true
mouse_follows_focus = true
animation_speed = 10

[swipe.gesture]
direction = "Reversed"

[bindings]
window_focus_first = "alt - i"
window_fullwidth = "cmd - return"
window_center = "alt - c"
window_focus_west = "cmd - h"
window_focus_east = "cmd - l"
window_resize = "alt - r"
window_manage = "alt + cmd - t"

window_swap_west = "alt + shift - h"
window_swap_east = "alt + shift - l"

quit = "ctrl + alt - q"
