[options]
focus_follows_mouse = true
mouse_follows_focus = true
animation_speed = 10

[swipe.gesture]
direction = "Reversed"

[bindings]
window_fullwidth = "cmd - return"
window_center = "alt - c"
window_focus_west = "cmd - h"
window_focus_east = "cmd - l"
window_resize = "alt - r"
window_manage = "alt + cmd - t"

window_swap_west = "alt + shift - h"
window_swap_east = "alt + shift - l"

window_virtualmovenum_1 = "alt + shift - 1"
window_virtualmovenum_2 = "alt + shift - 2"
window_virtualmovenum_3 = "alt + shift - 3"
window_virtualmovenum_4 = "alt + shift - 4"

window_virtualnum_1 = "alt - 1"
window_virtualnum_2 = "alt - 2"
window_virtualnum_3 = "alt - 3"
window_virtualnum_4 = "alt - 4"

window_virtual_north = "cmd + shift - k"
window_virtual_south = "cmd + shift - j"
window_virtualmove_north = "cmd + alt - k"
window_virtualmove_south = "cmd + alt - j"
quit = "ctrl + alt - q"
